# --- CONFIGURACIÓN PARA DMZ ---

# 1. Definimos la red DMZ                
acl red_dmz src 172.1.1.0/24

# 2. Definimos la lista blanca                  
acl dominios_updates_dmz dstdomain "/etc/squid/dominios-permitidos-dmz"

# 3. REGLA DE ACCESO:
# Permitir a la DMZ ir a los sitios de updates sin autenticación y sin horario
http_access allow red_dmz dominios_updates_dmz
