# 1 - Autenticación básica - Para saber si eres un usuario de ldap
auth_param basic program /usr/lib/squid/basic_ldap_auth \
 -b "ou=ou_usuarios,dc=miau,dc=org" \
 -D "cn=admin,dc=miau,dc=org" \
 -w "asir" \
 -f "uid=%s" \
 -h 172.2.1.2
# Rendimiento de la autenticación
auth_param basic realm Proxy Miau - Introduce tus credenciales
auth_param basic children 5

# 2 - Autenticación de grupo
# Buscamos en ou_grupos si el usuario suministrado está en cierto grupo
external_acl_type check_group %LOGIN /usr/lib/squid/ext_ldap_group_acl \
 -b "ou=ou_grupos,dc=miau,dc=org" \
 -D "cn=admin,dc=miau,dc=org" \
 -w "asir" \
 -f "(&(objectClass=posixGroup)(cn=%g)(memberUid=%u))" \
 -h 172.2.1.2

#########################
#Definición de ACLs
#########################
#Creanos ACL para nuestra red LAN
acl redLan src 172.2.1.0/24
#Crear ACL con dominios de redes sociales
acl filtro_rrss dstdomain "/etc/squid/dominios-denegados"
#Expresiones prohibidas en url
acl exp_no_permitidas url_regex "/etc/squid/block-exp"
#Horario de trabajo
acl horario_laboral time MTWHF 09:00-15:00
# ACL que obliga a loguearse
acl ldap_auth proxy_auth REQUIRED
# ACL que chequea el grupo especifico 'proxy_users'
acl admitidos_internet external check_group proxy_users

#########################
#Reglas de acceso
#########################
#Denegar conexiones fuera del horario laboral
http_access deny redLan !horario_laboral
#Denegar acceso a redes sociales
http_access deny filtro_rrss
#Denegamos expresiones no permitidas en url
http_access deny exp_no_permitidas
#Permitir solo si el usuario esta en LDAP y está en el grupo proxy_users
http_access allow redLan ldap_auth admitidos_internet
#Permitir navegación web para red LAN
#http_access allow redLan

